/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tiket.view;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALEXIS
 */
public class User extends javax.swing.JFrame {

    int id;
    boolean update = false;

    public User() {
        initComponents();
        JTableUser.removeColumn(JTableUser.getColumnModel().getColumn(0));
    }

    public void reset() {
        id = 0;
        txtUsername.setText(null);
        jPassword.setText(null);
        cbRole.setSelectedIndex(0);
    }

    public void refresh() {
        Connection connection = MysqlConnection.Connect();
        int index = 1;
        DefaultTableModel tblModel = (DefaultTableModel) JTableUser.getModel();
        tblModel.setRowCount(0);
        try {
            Statement stmnt = connection.createStatement();
            String query = "SELECT * FROM user";
            ResultSet result = stmnt.executeQuery(query);
            while (result.next()) {
                String id = String.valueOf(result.getInt("id"));
                String username = result.getString("username");
                String password = result.getString("password");
                String role = result.getString("role");
                String tbData[] = { id, String.valueOf(index), username, password, role };
                tblModel.addRow(tbData);
                index++;
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    public boolean validate(String username) {
        Connection connection = MysqlConnection.Connect();
        try {
            if (update) {
                String query = "SELECT * FROM user WHERE username = ? AND id = ?";
                PreparedStatement stmnt = connection.prepareStatement(query);
                stmnt.setString(1, username);
                stmnt.setInt(2, id);
                ResultSet rs = stmnt.executeQuery();
                if (rs.next()) {
                    return true;
                } else {
                    String query2 = "SELECT * FROM user WHERE username = ?";
                    PreparedStatement stmnt2 = connection.prepareStatement(query2);
                    stmnt2.setString(1, username);
                    ResultSet rs2 = stmnt2.executeQuery();
                    if (rs2.next()) {
                        return false;
                    } else {
                        return true;
                    }
                }
            } else {
                String query = "SELECT * FROM user WHERE username = ?";
                PreparedStatement stmnt = connection.prepareStatement(query);
                stmnt.setString(1, username);
                ResultSet rs = stmnt.executeQuery();
                if (rs.next()) {
                    return false;
                } else {
                    return true;
                }
            }

        } catch (Exception e) {
            System.out.println(e.getMessage());
            return false;
        }
    }

    /**
     * Creates new form Input_User
     * 
     * private void initComponents() {
     * throw new UnsupportedOperationException("Not supported yet."); // Generated
     * from
     * nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
     * 
     * 
     * 
     * }
     * 
     * 
     * /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnUpload4 = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        cbRole = new javax.swing.JComboBox<>();
        btnUpload = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        userButton = new javax.swing.JButton();
        keretaButton = new javax.swing.JButton();
        gerbongButton = new javax.swing.JButton();
        tujuanButton = new javax.swing.JButton();
        jadwalButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        JTableUser = new javax.swing.JTable();
        btnEdit = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPassword = new javax.swing.JPasswordField();
        clear = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        btnUpload4.setText("Refresh");
        btnUpload4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpload4ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Role", "user", "admin" }));
        cbRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRoleActionPerformed(evt);
            }
        });

        btnUpload.setText("Upload");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("User");

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        userButton.setText("User");

        keretaButton.setText("Kereta");
        keretaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keretaButtonActionPerformed(evt);
            }
        });

        gerbongButton.setText("Gerbong");
        gerbongButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerbongButtonActionPerformed(evt);
            }
        });

        tujuanButton.setText("Tujuan");
        tujuanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tujuanButtonActionPerformed(evt);
            }
        });

        jadwalButton.setText("Jadwal");
        jadwalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jadwalButtonActionPerformed(evt);
            }
        });

        logoutButton.setText("Log Out");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(keretaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gerbongButton, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(tujuanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jadwalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(userButton)
                .addGap(18, 18, 18)
                .addComponent(keretaButton)
                .addGap(18, 18, 18)
                .addComponent(gerbongButton)
                .addGap(18, 18, 18)
                .addComponent(tujuanButton)
                .addGap(18, 18, 18)
                .addComponent(jadwalButton)
                .addGap(18, 18, 18)
                .addComponent(logoutButton)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Password");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Username");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Role");

        JTableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "No", "Username", "Password", "role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTableUser.setToolTipText("");
        JTableUser.setCellSelectionEnabled(true);
        JTableUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableUserMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(JTableUser);

        btnEdit.setText("Edit");
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
        });
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        clear.setText("Clear");
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(169, 169, 169))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbRole, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPassword, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 16, Short.MAX_VALUE))
                                    .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.LEADING))
                                .addContainerGap())))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(196, 196, 196)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEdit)
                            .addComponent(btnRefresh)
                            .addComponent(btnUpload)
                            .addComponent(btnDelete)
                            .addComponent(clear)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tujuanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tujuanButtonActionPerformed
        Tujuan tuju = new Tujuan();
        tuju.setVisible(true);
    }//GEN-LAST:event_tujuanButtonActionPerformed

    private void keretaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keretaButtonActionPerformed
        Kereta ker = new Kereta();
        ker.setVisible(true);
    }//GEN-LAST:event_keretaButtonActionPerformed

    private void gerbongButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerbongButtonActionPerformed
        Gerbong ger = new Gerbong();
        ger.setVisible(true);
    }//GEN-LAST:event_gerbongButtonActionPerformed

    private void jadwalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jadwalButtonActionPerformed
        Jadwal jdw = new Jadwal();
        jdw.setVisible(true);
    }//GEN-LAST:event_jadwalButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        Login log = new Login();
        log.setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnUploadActionPerformed
        if (txtUsername.getText().isEmpty() || jPassword.getText().isEmpty() || cbRole.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Data yang anda masukkan belum lengkap\nSilahkan ulangi lagi");
        } else {
            Connection connection = MysqlConnection.Connect();
            try {
                if (validate(txtUsername.getText())) {
                    String sql = "insert into user (username, password, role) values (?, ?, ?)";
                    PreparedStatement pstmt = connection.prepareStatement(sql);
                    pstmt.setString(1, txtUsername.getText());
                    char[] passwordChars = jPassword.getPassword();
                    String password = new String(passwordChars);
                    pstmt.setString(2, password);

                    String grd;
                    grd = cbRole.getSelectedItem().toString();
                    pstmt.setString(3, grd);

                    pstmt.executeUpdate();

                    JOptionPane.showMessageDialog(null, "Data berhasil di masukan");
                    refresh();
                    reset();
                } else {
                    JOptionPane.showMessageDialog(null, "Username telah terdaftar !!!");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

    }// GEN-LAST:event_btnUploadActionPerformed

    private void cbRoleActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbRoleActionPerformed
        // TODO add your handling code here:

    }// GEN-LAST:event_cbRoleActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEditActionPerformed
        update = true;
        if (txtUsername.getText().isEmpty() || jPassword.getText().isEmpty() || cbRole.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Data yang anda masukkan belum lengkap\nSilahkan ulangi lagi");
        } else {
            Connection connection = MysqlConnection.Connect();
            try {
                if (validate(txtUsername.getText())) {
                    String sql = "UPDATE user SET username = ?, password = ?, role = ? WHERE id = ?";
                    PreparedStatement pstmt = connection.prepareStatement(sql);
                    pstmt.setString(1, txtUsername.getText());
                    char[] passwordChars = jPassword.getPassword();
                    String password = new String(passwordChars);
                    pstmt.setString(2, password);

                    String grd;
                    grd = cbRole.getSelectedItem().toString();
                    pstmt.setString(3, grd);
                    pstmt.setInt(4, id);

                    pstmt.executeUpdate();

                    JOptionPane.showMessageDialog(null, "Data berhasil di update");
                    refresh();
                    reset();
                    update = false;
                } else {
                    JOptionPane.showMessageDialog(null, "Username telah terdaftar !!!");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }// GEN-LAST:event_btnEditActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRefreshActionPerformed
        refresh();
    }// GEN-LAST:event_btnRefreshActionPerformed

    private void btnUpload4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnUpload4ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnUpload4ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDeleteActionPerformed

    }// GEN-LAST:event_btnDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jButton5ActionPerformed

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnEditMouseClicked

    }// GEN-LAST:event_btnEditMouseClicked

    private void JTableUserMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_JTableUserMouseClicked
        id = 0;
        int row = JTableUser.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) JTableUser.getModel();
        id = Integer.parseInt(model.getValueAt(row, 0).toString());
        txtUsername.setText(model.getValueAt(row, 2).toString());
        jPassword.setText(model.getValueAt(row, 3).toString());
        cbRole.setSelectedItem(model.getValueAt(row, 4));
    }// GEN-LAST:event_JTableUserMouseClicked

    private void clearMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_clearMouseClicked
        reset();

    }// GEN-LAST:event_clearMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnDeleteMouseClicked
        try {
            Connection connection = MysqlConnection.Connect();
            String query = "DELETE FROM user WHERE id = ?";
            PreparedStatement stmnt = connection.prepareStatement(query);
            stmnt.setInt(1, id);
            stmnt.execute();
            JOptionPane.showMessageDialog(null, "Data berhasil di hapus");
            reset();
            refresh();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }// GEN-LAST:event_btnDeleteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException
                | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>

        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new User().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableUser;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnUpload;
    private javax.swing.JButton btnUpload4;
    private javax.swing.JComboBox<String> cbRole;
    private javax.swing.JButton clear;
    private javax.swing.JButton gerbongButton;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton jadwalButton;
    private javax.swing.JButton keretaButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton tujuanButton;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JButton userButton;
    // End of variables declaration//GEN-END:variables

}
